server:
  port: 8084

spring:
  application:
    name: calculation
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: taxCalc
      port: 27017
      host: localhost
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
