server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: person
  data:
    mongodb:
      database: taxCalc
      port: 27017
      host: mongodb
      authentication-database: admin
      username: rootuser
      password: rootpass
      auto-index-creation: true
