server:
  port: 8082

spring:
  application:
    name: person
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: taxCalc
      port: 27017
      host: localhost
      auto-index-creation: true
  rabbitmq:
    addresses: rabbitmq:5672
